### ISSUE TITLE
Home "Aceptar" button is not working in small screens

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/maps-project#100]
**Describe the bug**
When I try to click in "Aceptar button" in a screen of 956x635px, it don't work.

I have checked and this happen because the truck and the boy is occupying space of the button and is over it

Please help us to solve this bug without break the home view

**To Reproduce**

1. Go to "Home" (`/`)
2. Open the inspect elements
3. Open the responsive design tool and start to work with the screen size, put a screen size of 900px
4. Try to click the button

**Expected behavior**
When click the button we're redirected to `/check` view

**Screenshots**
![imagen](https://user-images.githubusercontent.com/66505715/158875162-d2789811-f33f-4d5b-93c7-3b7bd3075693.png)
![imagen](https://user-images.githubusercontent.com/66505715/158875081-96e866d7-fefb-42c8-a166-9612eee362ba.png)

**Desktop (please complete the following information):**

- OS: Linux Cinnamon
- Browser: Firefox

**Additional context**
I think you could to use z-index to fix it, but if exist a better way it's so better

**Comment by heliomar-pena** [comment]
@Azordev/reviewers I would say that if the problem is solved using z-index the tasks would be of `E.E 1`, but if is a better solution the tasks can be of `E.E 2` since they should be careful with the responsive and the position of the element, what do you think?

**Comment by Eghinner** [comment]
I'm sorry, I didn't notice. I would like to solve it

**Comment by heliomar-pena** [comment]
@Eghinner How much E.E was take to you your solution?

**Comment by Eghinner** [comment]
EE 1 is fine. It was a mistake that I didn't notice

**Comment by heliomar-pena** [comment]
Don't worry. Thanks for the help, good job!
