### ISSUE TITLE
Organize chat view

### ISSUE THREAD

**Issue by e-azocar** [Azordev/maps-project#115]
### Explication

Currently, in the chat view we have 2 types of users: **dasher** and **user**, and each one of them has a different position. The dasher messages should be at left and user messages should be at right.

#### Original design
![image](https://user-images.githubusercontent.com/61360270/160466053-a38b15e1-ee67-4347-8573-22a049727d29.png)

####
![image](https://user-images.githubusercontent.com/61360270/160466434-2b385c87-6d46-4036-97d6-8f38787fe3e2.png)

### Checklist

Describe the key points to complete the task. This points will help in the pull request test.

This issue can be closed when the following tasks are complete:

- [ ] The dasher messages should be at left
- [ ] The user messages should be at right
- [ ] The position of the chat message should look like the layout

### References
**Path**: `/chat/testing`
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=771%3A593
![image](https://user-images.githubusercontent.com/61360270/160466658-dd05f428-a631-4511-b65a-d05b71bee3ca.png)
![image](https://user-images.githubusercontent.com/61360270/160466696-20dcdc78-87c3-4fa3-b908-7c736b108019.png)

**Comment by Eghinner** [comment]
I can also fix the styles to look like this ?
![screenshot-localhost_3000-2022 04 05-00_49_06](https://user-images.githubusercontent.com/71513679/161685172-ac8d6f81-6b88-409c-88d2-137855605db7.png)
Is just add padding, remove min-width and align avatar img
