### ISSUE TITLE
Add time and date in messages

### ISSUE THREAD

**Issue by e-azocar** [Azordev/maps-project#117]
### Explication

In the original design, at chat view, each one of the messages has and image (dasher or user), text, and message's time. From database we receive `updated_at`, and we could use it to show date and time of messages.

### Screenshots
![image](https://user-images.githubusercontent.com/61360270/160837064-c7e0634c-f8b3-48dc-bb21-cb42b7a02cbb.png)

### Checklist

Describe the key points to complete the task. This points will help in the pull request test.

This issue can be closed when the following tasks are complete:

- [ ] Add message date and time below
- [ ] Show the time and date in a format understandable for humans, for example using:
 ```javascript
new Date(updated_at).toLocalString("es-CO")
```
- [ ] Add the correct styles for time and date

#### Figma design
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=771%3A593
#### Date object documentation
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task @Katsu08 @e-azocar @Israel-Laguan
