### ISSUE TITLE
Place input placeholder to the left

### ISSUE THREAD

**Issue by e-azocar** [Azordev/maps-project#118]
### Explication

In check view, we have an input, which its placeholder are not correctly aligned.
If you find another input which should be fixed, please do it.

#### Original design
![image](https://user-images.githubusercontent.com/61360270/161132475-a40de65b-4765-4418-8619-1fc3a49a7972.png)

#### Current page
![image](https://user-images.githubusercontent.com/61360270/161141155-bc4a3090-bb4e-4dcb-ae6d-ffd116889bd2.png)

### Checklist

Describe the key points to complete the task. This points will help in the pull request test.

This issue can be closed when the following tasks are complete:

- [ ] Align the input placeholder to the left, like design
- [ ] Review all views and find inputs with the same problem to fix them

#### Figma design
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=1594%3A791

**Comment by arodriguezl9302** [comment]
I would like to be assigned to this task @Katsu08  @e-azocar @Israel-Laguan

**Comment by Eghinner** [comment]
'Confirm' has placeholder align center
![screenshot-www figma com-2022 04 05-09_51_11](https://user-images.githubusercontent.com/71513679/161769655-67bcf0df-f4ea-430e-b06a-1289e34333af.png)

**Comment by Israel-Laguan** [comment]
> 'Confirm' has placeholder align center ![screenshot-www figma com-2022 04 05-09_51_11](https://user-images.githubusercontent.com/71513679/161769655-67bcf0df-f4ea-430e-b06a-1289e34333af.png)

Maybe just try in responsive, please check @angelik0828
