### ISSUE TITLE
Improve Confirmation View

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#126]
Explanation:

 The size of the elements in general is different from what you see in the design, place the notebook image on the site, check the color of the text used in the title confirm receipt, the font size of the text "we are done" and the subtitle together.

Screenshots:
![view_start-desktop](https://user-images.githubusercontent.com/4030477/159799643-bd50cebe-d010-4553-bf91-1ed385e2ac71.png)
![image](https://user-images.githubusercontent.com/4030477/159799845-f1659f58-c8c6-4728-b133-aefef1155c88.png)

 Checklist:
  
 - [ ] Locate notebook view.
 - [ ] Check and change the color of the text used in Confirm receipt.
 - [ ] Font size "we are done" and subtitle.
 - [ ] Verify screen sizes:
 
### References:

How to get to this view in the application: /confirm/1

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=781%3A696

**Comment by Israel-Laguan** [comment]
Is this for desktop only? I think should create a new issue for responsive.
