### ISSUE TITLE
Add Loader in HTML with CSS

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#13]
We can add a loader to have a more native look on mobile, but it looks good on desktop as well.

## Checklist
- [ ] ] When you open the app, you have a loader like this:

![image](https://user-images.githubusercontent.com/36519478/134831898-771ed0ac-e2a2-4c7e-ab9b-aa5649f933bb.png)

**Comment by heliomar-pena** [comment]
@angelik0828 do you have a design for maps-project loader?

**Comment by angelik0828** [comment]
The change was made with the Azordev logo @Katsu08 @samuel-vergara-leon 
![image](https://user-images.githubusercontent.com/4030477/154561106-0217f98c-924a-4f4f-96a4-36009ea397ef.png)

**Comment by heliomar-pena** [comment]
I think it's a good loader. @samuel-vergara-leon can you do the changes at the tasks including the new loader image?
