### ISSUE TITLE
Screen exists but not long enough to be visible

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#140]
**Explanation:**
When the app starts, the screen exists but it doesn't last long enough, so it feels like it doesn't exist.

**Current result:**
When starting the application it does not show page 1, but loads page 2.
application it does not show page 1, but loads page 2.

**Expected result:**
That when starting the application the system shows page 1 where it exposes the Azordev logo.

*Screen size:*
All resolutions.
### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170147961-dee928be-800f-40a6-ae5d-37567e0f9108.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/170147999-8fbc6183-1f30-4b4b-99f2-67646a316ff3.png)

### Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the application starts on page 1]     

  ### References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46
Our:
 https://github.com/Azordev/maps-project

Spanish Version:

**Explicación:**
Cuando se inicia la aplicación, la pantalla existe pero no dura lo suficiente, por lo que parece que no existe.

**Resultado actual:**
Al iniciar la aplicación, no muestra la página 1, pero carga la página 2.
La aplicación no muestra la página 1, pero carga la página 2.

**Resultado Esperado:**
Que al iniciar la aplicación el sistema muestre la página 1 donde expone el logo de Azordev.

*Tamaño de pantalla:*
Todas las resoluciones.
### Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170147961-dee928be-800f-40a6-ae5d-37567e0f9108.png)
Nuestro:
![imagen](https://user-images.githubusercontent.com/74306449/170147999-8fbc6183-1f30-4b4b-99f2-67646a316ff3.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-[Verifica que la aplicación inicie en la página 1]

  ### Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Nuestro:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris I think it can be changed because it does not last long enough, the screen does exist

**Comment by e-azocar** [comment]
It doesn't depens on us
