### ISSUE TITLE
Different Size Checkbox  /  Casilla De Verificación De Diferente Tamaño

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#143]
**Explanation:**
The checkbox looks more extended downwards than in the original.

**Current result:**
Entering the third page, the checkbox is seen further down.

**Expected result:**
That when entering the third page, the check box is more limited with respect to the size of the original.
*Screen size:*
425x633 mobile
375x633 mobile
320x633 mobile

### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170158814-8083dca2-4787-4e00-857e-bcd4876b99c0.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/170158852-c4201ce1-01a3-47db-926b-bea925d4e6c1.png)

### Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the light blue box has the correct measurements]

### References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=420%3A148
Our:
 https://github.com/Azordev/maps-project

Spanish Version:

**Explicación:**
La casilla de verificación parece más extendida hacia abajo que en el original.

**Resultado actual:**
Entrando en la tercera página, más abajo se ve la casilla de verificación.

**Resultado Esperado:**
Que al entrar en la tercera página, la casilla de verificación esté más limitada con respecto al tamaño del original.
*Tamaño de pantalla:*
425x633 móvil
375x633 móvil
320x633 móvil

### Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170158814-8083dca2-4787-4e00-857e-bcd4876b99c0.png)
Nuestra:
![imagen](https://user-images.githubusercontent.com/74306449/170158852-c4201ce1-01a3-47db-926b-bea925d4e6c1.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[Verifica que el cuadro azul claro tenga las medidas correctas]

### Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=420%3A148
Nuestra:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris checkbox to check in list
