### ISSUE TITLE
Pop-Up Window "Before Receiving..."  /  Ventana Emergente "Antes De Recibir..."

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#144]
**Explanation:**
The popup referring to "Before you receive" is larger than the original shows.

**Current result:**
Entering the third page, the pop-up referring to "Before receiving" appears larger.

**Expected result:**
That when entering the third page, the pop-up window that refers to "Before receiving" looks smaller as shown in the original.

*Screen size:*
All screens for mobile.

### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170160272-1e956cd6-9730-4f2a-a809-e5218920126a.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/170160305-b9be9360-5dd2-493a-a880-712256463ec2.png)

### Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the popup referring to "Before receiving" is modified and is the correct size]

### References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
  https://github.com/Azordev/maps-project

**Explicación:**
La ventana emergente que hace referencia a "Antes de recibir" es más grande que la muestra original.

**Resultado actual:**
Al ingresar a la tercera página, la ventana emergente que hace referencia a "Antes de recibir" aparece más grande.

**Resultado Esperado:**
Que al ingresar a la tercera página, la ventana emergente que hace referencia a "Antes de recibir" se vea más pequeña como se muestra en el original.

*Tamaño de pantalla:*
Todas las pantallas para móvil.

 Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170160272-1e956cd6-9730-4f2a-a809-e5218920126a.png)
Nuestra:
![imagen](https://user-images.githubusercontent.com/74306449/170160305-b9be9360-5dd2-493a-a880-712256463ec2.png)

 Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[Verifica que el popup que hace referencia a "Antes de recibir" esté modificado y tenga el tamaño correcto]

Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Nuestro:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris I don't know if the idea is clear when saying white box, you can use pop-up or pop-up window

**Comment by e-azocar** [comment]
It depend on display resolution
