### ISSUE TITLE
Description In "Before Receiving"  /  Descripción En "Antes De Recibir"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#146]
**Explanation:**
In the "Before Receiving" box there is a line that has a different text, it says "RODADA" and in the original it says "Rut".

**Current result:**
When entering page 3 in the box "Before Receiving" under the name it says "RODADA".

**Expected result:**
That when entering page 3 in the box "Before Receiving" under the name say "Ruth".

*Screen size:*
Full screen.

### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170163360-bc0f9408-fc89-41c8-ab00-aa6289dbc841.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/170163384-b270e962-ab86-41b3-a7b2-6ca5a0d4f07e.png)
 Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the specified correction is made]

References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
  https://github.com/Azordev/maps-project

Spanish Version:

**Explicación:**
En la casilla "Antes de Recibir" hay una línea que tiene un texto diferente, dice "RODADA" y en el original dice "Rut".

**Resultado actual:**
Al ingresar a la página 3 en la casilla "Antes de Recibir" debajo del nombre dice "RODADA".

**Resultado Esperado:**
Que al ingresar a la página 3 en el recuadro "Antes de Recibir" debajo del nombre diga "Ruth".

*Tamaño de pantalla:*
Pantalla completa.

### Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170163360-bc0f9408-fc89-41c8-ab00-aa6289dbc841.png)

Nuestra:
![imagen](https://user-images.githubusercontent.com/74306449/170163384-b270e962-ab86-41b3-a7b2-6ca5a0d4f07e.png)
 Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-[Verificar que se haya realizado la corrección especificada]

Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Nuestra:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris the data that should be in that space has not been validated, but is not "RODADA", this should be changed.

**Comment by e-azocar** [comment]
The text "RODADA" is because the automatic translation
