### ISSUE TITLE
Popup on page

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#147]
### Explanation
Going to page 3 for 1024x633 resolution, you see a different popup than the one shown in the original.

current result:
Upon entering page 3, a different popup is seen.

Expected result:
That when entering page 3 you see a pop-up window the same as the one shown in the original.

*Screen size:*
1024x633 for laptop and bigger.

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/170165308-d4846fe2-9bb1-4b5a-8079-4141f1b4c15c.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/170165357-a10b8110-617e-4a10-afbe-285730dae319.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the specified correction is made]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris We are talking about transparency, I think this task could be more about what it looks like in this resolution than color.

**Comment by e-azocar** [comment]
Some display sizes show the header (light blue box), so that isn't a bug
