### ISSUE TITLE
Title and sub-title align with the delivery  / Títulos Y Subtítulos alinearse con la entrega

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#148]
** Explanation:**
When entering page 2 for 768x633 tablets, the title and subtitle are not aligned with the delivery, compared to the original.

**Current result:**
When entering page 2 it is observed that the title and the subtitle are not aligned with the delivery.

**Expected result:**
That when you enter page 2 you see the title and subtitle aligned with the delivery, as shown in the original.

*Screen size:*
768x633 for tablet
Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170358559-c009abea-24f5-4a78-87d6-b6a9aec985fb.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/170358518-2dd60d4b-0b18-41b6-99d3-411bab8f3789.png)

 Check list:
This issue can be closed when the following tasks are completed:
-[Check that the title and sub-title are aligned with the delivery]

References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
  https://github.com/Azordev/maps-project

Spanish Version:

** Explicación:**
Al ingresar a la página 2 para tabletas de 768x633, el título y el subtítulo no están alineados con la entrega, en comparación con el original.

**Resultado actual:**
Al ingresar a la página 2, se observa que el título y el subtítulo no están alineados con la entrega.

**Resultado Esperado:**
Que al entrar a la página 2 veas el título y subtítulo alineados con la entrega, tal como se muestra en el original.

*Tamaño de pantalla:*
768x633 para tableta

Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170358559-c009abea-24f5-4a78-87d6-b6a9aec985fb.png)

Nuestro:
![imagen](https://user-images.githubusercontent.com/74306449/170358518-2dd60d4b-0b18-41b6-99d3-411bab8f3789.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[Revisar que el título y subtítulo estén alineados con la entrega]

Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Nuestro:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris I think it would be to align with delivery, change to make it clearer
