### ISSUE TITLE
Adjust font size/  Ajustar tamaño de la fuente

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#149]
**Explanation:**
Entering page 2 for 768x633 tablets, the name of the button, "OK", is smaller.

Current result:
When entering page 2 the letter of the "Accept" button looks smaller.

Expected result:
That when entering page 2 the letter of the "Accept" button looks bigger as the original shows.

*Screen size:*
768x633 for tablet
Screenshots:

Original:
![image](https://user-images.githubusercontent.com/74306449/170359595-9c43d88f-d34d-4fc1-bd2f-55e602565d1c.png)
Our:
![image](https://user-images.githubusercontent.com/74306449/170359636-24730dff-f661-42cd-baba-ac5209e76b6b.png)

 Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the size of the button is modified]

   References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
  https://github.com/Azordev/maps-project

Spanish Version:

**Explicación:**
Al ingresar a la página 2 para tabletas de 768x633, el nombre del botón, "OK", es más pequeño.

resultado actual:
Al ingresar a la página 2 la letra del botón "Aceptar" se ve más pequeña.

Resultado Esperado:
Que al entrar a la página 2 la letra del botón "Aceptar" se vea más grande como muestra el original.

*Tamaño de pantalla:*
768x633 para tableta
Capturas de pantalla:

Original:
![imagen](https://user-images.githubusercontent.com/74306449/170359595-9c43d88f-d34d-4fc1-bd2f-55e602565d1c.png)
Nuestro:
![imagen](https://user-images.githubusercontent.com/74306449/170359636-24730dff-f661-42cd-baba-ac5209e76b6b.png)

 Lista de Verificación:
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[Verifica que se modifique el tamaño del botón]

   Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Nuestro:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris  I think the size is proportional to the size, it might be better to adjust the font size and you can suggest one.

**Comment by anaPiris** [comment]
> @angelik0828 de acuerdo Angelica.
