### ISSUE TITLE
Define CSS library

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#15]
We can use default CSS but we can opt-in to any good CSS solution for React. Some options are:

- CSS styling and CSS modules (default)
- SASS/SCSS (would need compiler in the pipeline)
- Ready-made library like Bootstrap or Material UI
- styled-components
- Something else

Until now team decided on styled-components but needs validation

Depends on #1

**Comment by heliomar-pena** [comment]
We have decided for emotion js or styled component, in the issue #16 this would be added
