### ISSUE TITLE
"Let Us Begin" Button Size  /  Tamaño Del Botón "Comencemos"

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#150]
**Explanation:**
Entering page 2 the "Empecemos" button looks larger in size and leaves less white space between the image and the page border.

**Current result:**
When entering page 2 the button "Empecemos" looks bigger.

**Expected result:**
That when entering page 2 the button "Empecemos" looks smaller as the original shows.

*Screen size:*
all mobile resolutions
tablet 768x633
Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170380678-6347c203-8b10-4744-9ae8-fc8c0867c40a.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/170380706-540ec81e-517e-4ae0-8367-b9382afb8642.png)
![image](https://user-images.githubusercontent.com/74306449/170552603-903665c4-c960-4f0e-98e2-563965de2f0e.png)

Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the size of the button is modified]

  References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Our:
  https://github.com/Azordev/maps-pro

---
Spanish Version:

**Explicación:**
Al ingresar a la página 2, el botón "Comencemos" aparece más grande y deja menos espacio en blanco entre la imagen y el borde de la página.

**Resultado actual:**
Al ingresar a la página 2, el botón "Comencemos" se hace más grande.

**Resultado Esperado:**
Que al entrar a la página 2 el botón "Comencemos" se ve más pequeño como muestra el original.

*Tamaño de pantalla:*
todas las resoluciones móviles
tableta 768x633
Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170380678-6347c203-8b10-4744-9ae8-fc8c0867c40a.png)

Nuestra:
![imagen](https://user-images.githubusercontent.com/74306449/170380706-540ec81e-517e-4ae0-8367-b9382afb8642.png)
![imagen](https://user-images.githubusercontent.com/74306449/170552603-903665c4-c960-4f0e-98e2-563965de2f0e.png)

Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-[Verifica que se modifique el tamaño del botón]

  Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=420%3A148
Nuestro:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris the problem may be the angle in the vertices and the width of the button is not adequate, try to put as close as possible or use references of the buttons in the other views.

**Comment by anaPiris** [comment]
@angelik0828 for all mobile and tablet views it looks the same, the width of the button is not correct and the alignment.
