### ISSUE TITLE
Title Alignment  /  Alineación De Títulos

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#151]
### Explanation:
When entering page 3, the title and sub-title are aligned above and to the left of the page, the original shows it in another position.

**Current result:**
Upon entering page 3, the title and sub-title are aligned at the top and left of the page.

**Expected result:**
That when entering page 3, the title and sub-title are aligned in the position shown in the original.

*Screen size:*
1024x633 and larger.

### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/170572798-fac33365-363c-4abb-84aa-21dc015fa50c.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/170572846-a7b5222b-2ed8-4e26-9dc3-b7205e6e31b8.png)
![image](https://user-images.githubusercontent.com/74306449/170573078-029a9ca5-4dae-43fb-a26e-89985ac89217.png)

### Check list:
This issue can be closed when the following tasks are completed:
-[ ] Verify that the text is in the position as indicated in the original
-[ ] Perform verification on the different types of screen

### References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

 ------------                              
 ###                          Spanish Version:

### Explicación:
Al ingresar a la página 3, el título y el subtítulo se alinean arriba y a la izquierda de la página. El original lo muestra en otra posición.

**Resultado actual:**
Al ingresar a la página 3, el título y el subtítulo se alinean en la parte superior e izquierda de la página.

**Resultado Esperado:**
Que al ingresar a la página 3, el título y subtítulo estén alineados en la posición que se muestra en el original.

*Tamaño de pantalla:*
1024x633 y mayor.

## Capturas de pantalla
Original:
![imagen](https://user-images.githubusercontent.com/74306449/170572798-fac33365-363c-4abb-84aa-21dc015fa50c.png)

Nuestra:
![imagen](https://user-images.githubusercontent.com/74306449/170572846-a7b5222b-2ed8-4e26-9dc3-b7205e6e31b8.png)
![imagen](https://user-images.githubusercontent.com/74306449/170573078-029a9ca5-4dae-43fb-a26e-89985ac89217.png)

## Lista de Verificación
Este problema se puede cerrar cuando se completan las siguientes tareas:
-[ ] Verificar que el texto esté en la posición indicada en el original
-[ ] Realizar verificación en los diferentes tipos de pantalla

## Referencias
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Nuestro:
https://github.com/Azordev/mapas-proyecto

**Comment by Israel-Laguan** [comment]
I suggest EE-2 or EE-3 if responsive included

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174320981-f0dfa24b-9eb3-4a8d-b348-4bd63489873a.png)
fixed!!!
