### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#152]
### Explanation
When entering page 3, under the "Before Receiving" pop-up window, below on the left, an empty space is observed, instead an image is seen in the original.

**Current result:**
Entering page 3, below the "Before Receiving" pop-up you see an empty space.

**Expected result:**
That when entering page 3, below to the left of the "Before Receiving" pop-up window, you can see an image as shown in the original.

*Screen size:*
1024x633 and larger.

### Screenshots
Expected:
![image](https://user-images.githubusercontent.com/74306449/170577143-a8280e13-9d0c-48f4-badb-60d9f68e3467.png)
![image](https://user-images.githubusercontent.com/74306449/171912312-3b402bb9-72de-49ee-a7f7-4fcad13128b5.png)

Current:
![image](https://user-images.githubusercontent.com/74306449/172262028-d436f988-78ba-4c80-8310-002ad737346e.png)
![image](https://user-images.githubusercontent.com/74306449/172262076-b6ca0599-c0ab-484e-8f78-14cc6b9469b0.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the image is placed in the correct place]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by Israel-Laguan** [comment]
I suggest EE-2

**Comment by angelik0828** [comment]
@anaPiris  check if that resolution is desktop if so the view must be divided into two parts and have the image, I notice that it is not the same view

**Comment by anaPiris** [comment]
@angelik0828 es resolución de escritorio, se ve diferente porque para esta vista cambia el fondo de pantalla, esta reportado en otra issue.

**Comment by angelik0828** [comment]
@anaPiris in the resolution mentioned below is a tablet on which the image should not be, on the other hand the image is not yet defined if it should be placed, but only in desktop view, fix the description so that it only adds the image in computer resolution.
![image](https://user-images.githubusercontent.com/4030477/172208430-7cf53eb2-3522-4d39-9985-9bbecbe05247.png)

**Comment by anaPiris** [comment]
@angelik0828 cambie la muestra de las resoluciones.

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174321918-283bd0b4-fa0f-422f-9c70-dc19dc3babdc.png)
 fixed!!
