### ISSUE TITLE
Content alignment

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#153]
### Explanation
When entering page 3, behind the pop-up window "Before receiving", you can see part of a text and a data entry field, for the 1024x633 resolution, while in higher resolutions this information is seen more to the right, but different from how the original shows it.

**Current result:**
1) Entering page 3, behind the "Before receiving" pop-up window for 1024x633 resolution, you can barely see part of a text and an input field.
2) For higher resolutions it looks more aligned to the right, but different from how the original shows it.

**Expected result:**
That when you enter page 3, you see behind the "Before You Receive" pop-up window but aligned to the right, the text, the ticket entry field, the pop-up window in red for ticket entry errors and the button ok, this for resolution 1024x633 and higher.

*Screen size:*
1) 1024x633 
2) 1044x633
3) 2560x633

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/170592342-53325665-6fcc-4e01-8116-a5fc5aa3e74b.png)

Our:
1)1024x633
![image](https://user-images.githubusercontent.com/74306449/170592370-4d95679e-25ee-4938-a2fa-c35b48028e06.png)

2) 1044x633
 ![image](https://user-images.githubusercontent.com/74306449/170593649-f1b5beda-5cc7-41ac-9899-20d5fa4f5afd.png)

3)2560x633
![image](https://user-images.githubusercontent.com/74306449/170593844-af00907b-b2aa-460f-a55d-fbdb8cd9b115.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the spaces are modified and displayed correctly]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by Israel-Laguan** [comment]
This is the intended behavior for those viewports, @angelik0828 please confirm. I think this issue is INVALID.

**Comment by angelik0828** [comment]
@anaPiris it looks different because it is the desktop view and the mobile view, they behave as they should
