### ISSUE TITLE
Missing text indicating ticket entry error

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#154]
### Explanation
When entering page 3, behind the "Before receiving" pop-up window, below the data entry field, a line of text is missing that indicates when a data is not correct marked in red.

**Current result:**
Entering page 3, behind the "Before receiving" pop-up below the data entry field, there is no text line indicating when an entered data is not correct, marked in red.

**Expected result:**
That when entering page 3, behind the "Before receiving" pop-up window below the data entry field, you can see the text line that indicates when a data is not correct marked in red.

*Screen size:*
1) 1024x633
2) 1044x633
3) 2560x633

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/170592342-53325665-6fcc-4e01-8116-a5fc5aa3e74b.png)

Our:
1)1024x633
![image](https://user-images.githubusercontent.com/74306449/170592370-4d95679e-25ee-4938-a2fa-c35b48028e06.png)

2) 1044x633
 ![image](https://user-images.githubusercontent.com/74306449/170593649-f1b5beda-5cc7-41ac-9899-20d5fa4f5afd.png)

3)2560x633
![image](https://user-images.githubusercontent.com/74306449/170593844-af00907b-b2aa-460f-a55d-fbdb8cd9b115.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the missing line was added]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by Israel-Laguan** [comment]
The red text was not intended to be ALWAYS present, most likely an example.

@angelik0828 please confirm, I think this issue is INVALID

**Comment by angelik0828** [comment]
@anaPiris  it is so that text is an error validation it does not appear because no error validation has been done the issue is invalid
