### ISSUE TITLE
Wrong name on button

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#155]
### Explanation
When entering page 3, after clicking on the "Got it" button in the "Before receiving" pop-up window, you must enter the ticket number, after this there is a button to confirm the entry, this button has the different name from the original.

**Current result:**
When entering page 3, after clicking on the "Got it" button in the pop-up window "Before receiving", you must enter the ticket number, after this there is a button to confirm the entry, this button has a name "Let us begin".

**Expected result:**
That when entering page 3, after clicking on the "Got it" button in the "Before receiving" pop-up window, you must enter the ticket number, after this there is a button to confirm the entry, this button has as name "OK".
*Screen size:*
1024x633 and higher.

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/171918897-8f139029-2164-4eda-ba85-f3887f4c0afe.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/171918952-ba4e9a52-7733-4ad3-9810-2a5e562c0132.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the change is made and is seen correctly]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
   https://github.com/Azordev/project-maps

**Comment by Israel-Laguan** [comment]
I propose EE-1

@angelik0828 please check that reproduction steps are clear

**Comment by anaPiris** [comment]
@Israel-Laguan pasos para repoducir modificado.

**Comment by angelik0828** [comment]
@anaPiris 
the correct text is let's start there was no change what to do
