### ISSUE TITLE
Different text color

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#156]
### Explanation
When entering page 3, the text behind the pop-up window that says "Enter ticket number" is in a different color from the original.

**Current result:**
Upon entering page 3, the text behind the pop-up window that says "Enter ticket number" turns blue.

**Expected result:**
That when entering page 3, the text behind the pop-up window that says "Enter ticket number" is seen in black, the same as the original.

*Screen size:*
1024x633 and higher

### Screenshots
Expected

![image](https://user-images.githubusercontent.com/74306449/171066896-c49f9b60-c913-4a86-b4f6-85029a2334d6.png)

Current
![image](https://user-images.githubusercontent.com/74306449/171066960-f3b45a17-e4e6-48dd-aa5d-3e9946e424b0.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the color change is made and is seen correctly]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by Israel-Laguan** [comment]
I think in cases like this a better language to use is

"Expected" vs "Current", when we are comparing the desired design

Instead than

"Original" vs "Our", which works when you are comparing 2 existing pages

@angelik0828 Please check if any update is needed in the template for issues

**Comment by Israel-Laguan** [comment]
I suggest EE-1

**Comment by angelik0828** [comment]
I think the theme is as it is being written because you should put what you want to see, which is the color of the text #005D9D and the one I see is behind a transparency, therefore it is not the same color, when inspecting it is the same color.
![image](https://user-images.githubusercontent.com/4030477/172210821-91bb614c-2bc7-40f2-960e-e9d29fdcc8b5.png)
