### ISSUE TITLE
Different Text  /  Texto Diferente

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#157]
### Explanation:
When entering page 3, the text behind the pop-up window that says "Insert ticket number" has a different description than the original.

**Current result:**
When entering page 3, the text behind the pop-up window says "Insert ticket number" different from the original.

**Expected result:**
That when entering page 3, the text behind the pop-up window says "Insert ticket number" equal to the original.

*Screen size:*
1024x633 and higher

### Screenshots:
Original:
![image](https://user-images.githubusercontent.com/74306449/171067722-7d231c3f-463d-403d-85f5-2cf65e59d5f1.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/171067740-969da4c1-2856-4051-97af-c96ce7ac140f.png)

### Check list:
This issue can be closed when the following tasks are completed:
-[Verify that the text change is made and read correctly]

  
### References:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

---

### Explicación:
Al ingresar a la página 3, el texto detrás de la ventana emergente que dice "Insertar número de boleto" tiene una descripción diferente a la original.

**Resultado actual:**
Al ingresar a la página 3, el texto detrás de la ventana emergente dice "Insertar número de boleto" diferente al original.

**Resultado Esperado:**
Que al ingresar a la página 3, el texto detrás de la ventana emergente dice "Insertar número de boleto" igual al original.

*Tamaño de pantalla:*
1024x633 y superior

### Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/74306449/171067722-7d231c3f-463d-403d-85f5-2cf65e59d5f1.png)

Nuestras:
![imagen](https://user-images.githubusercontent.com/74306449/171067740-969da4c1-2856-4051-97af-c96ce7ac140f.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
-[Verifica que el cambio de texto se haga y se lea correctamente]

### Referencias:
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Nuestro:
https://github.com/Azordev/mapas-proyecto

**Comment by Israel-Laguan** [comment]
I suggest EE-1

**Comment by Eghinner** [comment]
The text is different in the mobile version and in the desktop version. Also the color. Which one should be correct? Or should it change depending on the device?
![N1a9Ibl0V8](https://user-images.githubusercontent.com/71513679/173902423-d596b09e-cf55-490d-853e-948a66e4868e.png)
?

**Comment by angelik0828** [comment]
@Eghinner  no, it must be the same in both the correct color is #005D9D , Poppins bold in uppercase

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174801037-2f87bc84-5f2f-4402-b9b4-8e0563b57485.png)
