### ISSUE TITLE
Error with alert icon below text field

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#158]
### Explanation
At the point where the ticket number is entered, it doesn't display the error message below the text when this happens.
Reproduction Steps:
1) start the app
2) enter the ticket number (or leave the field empty)
3) When clicking on the enter button it shows me a toas, it says that there is an error in the entry of the ticket or the field is empty but it does not appear below the text field, the error text in red letters.

**Current result:**
When starting the application, entering a wrong ticket number or leaving this field empty and pressing enter, it does not display an error message in red letters below the text field.

**Expected result:**
When starting the application, entering a wrong ticket number or leaving this field empty and pressing enter, which shows an error message in red letters below the text field.

*Screen size:*
for all resolutions

### Screenshots
Original:
![image](https://user-images.githubusercontent.com/74306449/171922528-a5939ac9-424b-49cc-8d4f-83f4a3625ba3.png)

Our:
![image](https://user-images.githubusercontent.com/74306449/171922346-d2ecec41-959f-4023-8219-cfb9e144d30c.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that in front of an error the text is seen in red letters.]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by Israel-Laguan** [comment]
I suggest EE-1

**Comment by Israel-Laguan** [comment]
@angelik0828 please be sure to have complete reproduction steps for this one

**Comment by anaPiris** [comment]
@Israel-Laguan modificado pasos para reproducir y capturas de pantalla.

**Comment by angelik0828** [comment]
@anaPiris post the playback steps for this please

**Comment by anaPiris** [comment]
@angelik0828 modifique explicacion y agregue pasos a reproducir, en realidad en el resultado actual muestra el resultado en un solo lugar, la sugerencia es porque en el ejemplo lo muestra en dos lugares diferentes.

**Comment by angelik0828** [comment]
@anaPiris Remember that the validation is done and the answer is shown in the toas and in the field when it is empty or not valid but it is maintained, it is not deleted like the other.

I think the name is not correct with what needs to be fixed, please check and change.
