### ISSUE TITLE
Ticket popups

### ISSUE THREAD

**Issue by anaPiris** [Azordev/maps-project#163]
### Explanation
When entering page 3, after entering an incorrect ticket number and clicking "OK", it shows a pop-up window in the upper right part of the page, but clicking more often adds more pop-up windows that are deleted after some seconds.

**Current result:**
When entering page 3, after entering an incorrect ticket number and clicking "OK", it shows a pop-up window at the top right of the page, continuing to click "OK" continues adding the same pop-up windows.

**Expected result:**
That when entering page 3, after entering an incorrect ticket number and clicking "Accept", it shows a pop-up window in the upper right part of the page, and when clicking "Accept" again, it does not add more windows emerging for the same reason.

*Screen size:*
for all resolutions

### Screenshots
Current:
![image](https://user-images.githubusercontent.com/74306449/171924539-ba8f03bc-1762-4452-8a2b-4f37227548a7.png)
![image](https://user-images.githubusercontent.com/74306449/171924598-251beea7-836b-47f7-bf03-db9d5e947223.png)

Expected:
![image](https://user-images.githubusercontent.com/74306449/171924921-dfe41ca8-6f93-48b6-ad8e-a6525d44c6f1.png)

### Check list
This issue can be closed when the following tasks are completed:
-[Verify that the changes are made and only one pop-up window is seen per situation]

  
### References
Original:
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-project?node-id=407%3A46
Our:
https://github.com/Azordev/maps-project

**Comment by angelik0828** [comment]
@anaPiris It's not a pop-up window, it's a toas, it will show up every time it finds validation and as you press the button several times and this the same error will continue to appear.
