### ISSUE TITLE
Arreglo imagen para medida 320 x 538

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/maps-project#164]
### Explanation

Se evidencia que el texto de "Revisemos como viene tu envío" se sobre pone a la imagen de la gorra del domiciliario.

**Actual result:**

Texto sobrepuesto en la imagen del domicilario en las medidas 320 x 538

**Expected result:**

Arreglo del tamaño del texto para que no suceda este inconveniente

*Screen size:*

Responsive 320 x 538

### Screenshots

![image](https://user-images.githubusercontent.com/101886534/172723555-ce67acb8-6aad-4a65-a936-dc46b781d5e9.png)

### Checklist

 This issue can be closed when the following tasks are complete:
 
 - [ ] Arreglo del tamaño del texto para que no suceda este inconveniente en las medidas 320 x 538

### References
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 please place the reference to the design because that link does not open unless the project is running on your PC in the gitpod tool.
