### ISSUE TITLE
Arreglo tamaño copys y CTA para medida 2560 x 1345

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/maps-project#165]
### Explanation
El texto, la imagen del camión, el CTA en las medidas 2560 x 1345 se ven muy pequeñas lo cual genera una mala experiencia de usuario.

**Actual result:** 

Texto copys, imagen del camión, CTA en las medidas 2560 x 1345 no tienen las dimensiones adecuadas.

**Expected result:** 

Arreglo y sincronia entre los elementos que componen la pantalla en las medidas mencionadas

*Screen size:* 

Responsive 2560 x 1345

### Screenshots

![image](https://user-images.githubusercontent.com/101886534/173250535-0b17f264-0853-4363-a686-69e210e8b7d8.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] Arreglo y sincronia entre los elementos que componen la pantalla en las medidas  2560 x 1345 (Tamaño copys, tamaño camión, tamaño CTA)

### References

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 please place the reference to the design because that link does not open unless the project is running on your PC in the gitpod tool.
