### ISSUE TITLE
Adjust Header Styles In Map  /  Ajustar Estilos De Encabezado En El Mapa

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#166]
### Explanation:

When entering the text, it is bigger and in an inappropriate position.

**Current result:**
The text is too big and does not fit in the header.

**Expected result:** 

When entering the title text it must be in a proportional 16px size and aligned with a 20px space to the top left and the header with a size of 24%.

Resolution:
 (520X538) - (768x538)

### Screenshots:

![image](https://user-images.githubusercontent.com/4030477/173417637-259524f9-fc12-4007-bee0-df63fefdbfa4.png)
![image](https://user-images.githubusercontent.com/4030477/173420665-d8e4f6ea-485e-4b08-bf07-f04d6a0e7128.png)

Our:
![image](https://user-images.githubusercontent.com/4030477/173420918-a1c65987-ddd0-4b01-bf91-61a5e99fdb54.png)

### Checklist:

- [ ] Adjust text size in title and subtitle.
- [ ] Adjust header height: 24%.
- [ ] Align left on mobile screen
- [ ] Adjust line spacing.
- [ ] Enlarge header container, guided by layout.
- [ ] Check mobile view from 320X538 to 768X538.

### References:

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46

---

# Spanish Version:

### Explicación:

Al ingresar el texto, es más grande y en una posición inapropiada.

**Resultado actual:**
El texto es demasiado grande y no cabe en el encabezado.

**Resultado Esperado:**

Al ingresar el texto del título debe estar en un tamaño proporcional de 16px y alineado con un espacio de 20px arriba a la izquierda y el encabezado con un tamaño de 24%.

Resolución:
 (520X538) - (768x538)

### Capturas de pantalla:

![imagen](https://user-images.githubusercontent.com/4030477/173417637-259524f9-fc12-4007-bee0-df63fefdbfa4.png)
![imagen](https://user-images.githubusercontent.com/4030477/173420665-d8e4f6ea-485e-4b08-bf07-f04d6a0e7128.png)

Nuestras:
![imagen](https://user-images.githubusercontent.com/4030477/173420918-a1c65987-ddd0-4b01-bf91-61a5e99fdb54.png)

### Lista de Verificación:

- [ ] Ajustar el tamaño del texto en título y subtítulo.
- [ ] Ajustar la altura del encabezado: 24%.
- [ ] Alinear a la izquierda en la pantalla del móvil.
- [ ] Ajustar interlineado.
- [ ] Ampliar contenedor de encabezado, guiado por diseño.
- [ ] Comprobar vista móvil de 320X538 a 768X538.

### Referencias:

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46

**Comment by anaceciliamolinares** [comment]
En este issue falta la validación del Dev. Check para poder seguir el work flow como lo esperamos.
