### ISSUE TITLE
Arreglar pantalla de laptop medidas 1024 x 538

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/maps-project#167]
### Explanation

Se evidencia que la visual actual para versión laptop es diferente a la versión planteada en el figma.

**Actual result:**

Elementos desorganizados y diferentes a la visual del figma en la versión laptop medidas 1024 x 538

**Expected result:**

Arreglo acorde a lo establecido en el figma
*Screen size:*

Responsive 1024 x 538

### Screenshots

**Versión actual** 

![image](https://user-images.githubusercontent.com/101886534/173425443-ddc8c9ac-552f-438d-aab5-ca18768145e3.png)

**Corrección según Figma**

![image](https://user-images.githubusercontent.com/101886534/173425561-11ba10ec-d687-4bc5-a139-fbc1583d2297.png)

### Checklist

 This issue can be closed when the following tasks are complete:
 
 - [ ] Arreglo de elementos para que concuerde con la versión del figma

### References
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 specify what a mobile view looks like in a desktop view
