### ISSUE TITLE
Agrandar copys y alinear elementos para medida 2560 x 1345 de acuerdo a figma versión desktop

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/maps-project#168]
### Explanation
El tamaño de texto y la alineación de los elementos no concuerda con figma

**Actual result:** 

El texto se ve muy pequeño y en ubicación diferente al figma de igual manera la caja para llenar el número de pedido.

**Expected result:** 

Arreglo y sincronia entre los elementos que componen la pantalla en las medidas mencionadas y con los textos organizados según figma

*Screen size:* 

Responsive 2560 x 1345

### Screenshots

**Actualmente**

![image](https://user-images.githubusercontent.com/101886534/173430475-6b79a324-e009-4501-9140-480d34217ca7.png)

**Versión Figma**

![image](https://user-images.githubusercontent.com/101886534/176045830-89a10dae-8889-44d6-bd64-c470bd863197.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] Ajustar tamaños en el texto y en el conjunto de elementos cercanos a la caja de llenado de pedido.
- [ ] Contrastar distribución de elementos y tamaños en la pantalla para que este acorde al figma para la versión Desktop.

### References

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 please specify which elements should be expanded
