### ISSUE TITLE
Imagen de fondo en las versiones de laptop no concuerdan con el figma

### ISSUE THREAD

**Issue by Ricardo-Gomez1** [Azordev/maps-project#169]
### Explanation
La imagen de fondo que se ve en el figma con una lupa, en la pantalla actual no se observa.

**Actual result:** 

En las versiones laptop no se observa la imagen de fondo propuesta en el figma.

**Expected result:** 

Adicionar y alinear la versión actual al figma.

*Screen size:* 

Responsive versiones laptop

### Screenshots

**Vista actual** 

![image](https://user-images.githubusercontent.com/101886534/173435622-f0b9a4c9-165b-4cc1-9633-cd64233d81b5.png)

**Vista Figma**

![image](https://user-images.githubusercontent.com/101886534/173435732-b79dc916-2a91-42cf-9e0e-88b36e793537.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [ ] Agregar imagen de fondo con el mapa y la lupa a las versiones laptop como se observa en el figma.

### References

https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/maps-proyect?node-id=407%3A46

**Comment by angelik0828** [comment]
@Ricardo-Gomez1 this has already been reported!!
