### ISSUE TITLE
Design artifacts HERE

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#17]
The designer decided to use Figma, this is for keeping track of the last design available.

## Designs available (click image to follow link)

Mobile views:
[![imagen](https://user-images.githubusercontent.com/66505715/152866973-e52a3fe7-c877-4b6e-a5ba-00726aef4dae.png)](
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46)

**Comment by Katsu08** [comment]
This issue need a eddit of pictures and links
