### ISSUE TITLE
Check And Make The Rafters In The Header   

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#48]
### Explanation:
The rounded box (header) has two square corners at the top and two rounded corners at the bottom. This, unlike the previous design, since its rounded box was a little more irregular, some had 3 square vertices and one rounded, and it varied according to each section. The functionality of the rounded box can be diverse and above all striking, since it contains a clear welcome message and information at the same time, this message is “HELLO! enter the ticket number.

### SCREENSHOTS 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/97471255/153661232-b4879e4c-7e6f-464d-aec6-5d5a3ad53de4.png">

### CHECKLISTE

- [ ] Unlike the previous design, the color of the rounded box (header) in the view_start--modal section is a lighter blue and an unspecified color code.

- [ ] Now the start and start error view have a tertiary_azordev color with code #9DBDFD, I feel a more relaxing color and not so strong.

- [ ] Change the back button that is in the upper left, with the arrowhead pointing to the left. This date tip is inside a circle.

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=434%3A1844

**Comment by heliomar-pena** [comment]
Can you add the specify color code of this task? @samuel-vergara-leon 


> - [ ]  Unlike the previous design, the color of the rounded box (header) in the view_start--modal section is a lighter blue and an > unspecified color code.

**Comment by heliomar-pena** [comment]
I think this task is already done
