### ISSUE TITLE
Update and Observe The View Map 

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#53]
### Explanation:
This is the map that is tracked, each one will have a status: picked up, on the way and we have arrived. The visual change of colors and icons will be done in the third window when it is in the state we have reached.
You will be able to obtain the graphic resources and respective sizes in the mobile view, in the attached Figma file.

### SCREENSHOTS
|![View_map--collecting](https://user-images.githubusercontent.com/4030477/155576408-3a693b0f-9e31-4ac4-ab4d-56b852ab0f51.png)|
![View_map--on_the_way](https://user-images.githubusercontent.com/4030477/155576436-48086288-08e4-4195-9732-06ccdeee8980.png)|

![View_map--confirmation](https://user-images.githubusercontent.com/4030477/155596980-ca76ac41-3c67-41d9-8c0e-f34449841aa9.png)

### CHECKLIST

- [ ] Header and footer color change #9DBDFD.
- [ ] Change font and font sizes type: Poppins bold and regular #003B62

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=522%3A28
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by ygamboalh** [comment]
I want to be assigned to this task
