### ISSUE TITLE
Update And Check The Home View

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#54]
### Explanation:
In this view a complete image change was made, the delivery image must be replaced, background change and as well as change of text styles and mobile view. Check that the different screens, including the desktop view, look good.
A link to the Figma design is attached to download the different graphic resources and check styles, 

### SCREENSHOTS 
<img width="307" alt="image" src="https://user-images.githubusercontent.com/97471255/154341215-70e086c5-41f9-4db1-891e-ae7943ae10d4.png">

### CHECKLIST 
- [ ] Change the background using the color `#9DBDFD` .
- [ ] Change text styles to bold and medium popins `#002740`
- [ ] Change of images.
- [ ] Remove the Dasher Logo
- [ ] Should look like the design

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=434%3A1844
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=448%3A4112

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by ygamboalh** [comment]
I want to be reassigned to this task.

**Comment by anaceciliamolinares** [comment]
Me parece muy bonito tanto el fondo como la atención para garantizar que todo lo elaborado funcione bien para tí.

**Comment by ygamboalh** [comment]
Please, unassign me this task
