### ISSUE TITLE
Update And Check The Arrived Modal

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#56]
### Explanation:
Arrival confirmation window, once the map generates that state the confirmation window appears, styles and existing image, and button styles must be changed, organize the content of the view that looks good in different mobile resolutions, take into account spaces and margins in the design.

A design link in figma is attached where you can also have access to graphic resources.

### SCREENSHOTS
<img width="277" alt="image" src="https://user-images.githubusercontent.com/97471255/154492440-64f103c9-bd82-48d3-94cd-e2f8f92410ac.png">

### CHECKLIST 

- [ ] Change the color of the "accept" button to a blue color with code `#005D9D`
- [ ] Change Delivery image.
- [ ] Transparency wallpaper for popup window #0000FF opacity at 17%.

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=420%3A249
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=522%3A28

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by ygamboalh** [comment]
I want to be reassigned to this task.

**Comment by ygamboalh** [comment]
Please, unassign me this task.
