### ISSUE TITLE
Update And Check Toast Error Message

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/maps-project#57]
### Explanation:
Validation of errors in existing form, there is already a library that does the Toast, the texts and error icon must be added when validating for empty fields.

Graphic and design resources are available from the Figma link at the bottom.

### SCREENSHOTS 
![view_report_error](https://user-images.githubusercontent.com/4030477/155599032-6d396903-181e-4dfe-8ecf-0d317cc28eda.jpg)

### CHECKLIST 

- [ ] Place styles in Toas existing regular and shadow Popins font.
- [ ] Add error message under text fields along with icon color #FF0B0B regular Popins font.

- [ ] The above must be shown when performing a validation of the text fields, that is to say that there is information in them and they are not sent empty.

### REFERENCES
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46
https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=448%3A4112

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task

**Comment by heliomar-pena** [comment]
> I want to be assigned to this task

Hello! I have seen that you have other 3 more issues assigned, please end those issues to can be assigned to another new issue
