### ISSUE TITLE
Organize Chat View.

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#79]
### Explanation:

The chat is upside down. The user chat should be located on the right side and the Delivery on the left side, check that it looks good in the different resolutions, I attach a Figma link if necessary for the view, el icono que aparece en la parte superior no es de el usuario ,es de el delivery, realizar ese cambio de imagen.

### Screenshots
![Vista chat](https://user-images.githubusercontent.com/4030477/156787766-e7c29769-da69-43bf-835b-ab384bdb5b36.png)

### Checklist

- [ ] Change user chat and delivery site.
- [ ] Change the icon used in the header.

### References:

(https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=420%3A332)

**Comment by Katsu08** [comment]
This task is not already done? I will check

**Comment by heliomar-pena** [comment]
I confirm that the chat bubbles are upside down

![image](https://user-images.githubusercontent.com/66505715/156782516-19bcccac-13f9-4037-a345-8c21165228e2.png)

**Comment by heliomar-pena** [comment]
Too please change the avatar at the header for the Delivery image

**Comment by arodriguezl9302** [comment]
I would like to do this task

**Comment by mdibuhossain** [comment]
I want to be assigned
