### ISSUE TITLE
Update Application Loading View

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#81]
### Explanation:

Change the icon and color at the start of the application, check that the views in the different resolutions work and look good, Resources available at the Figma link. 

### Screenshots

![View_Home](https://user-images.githubusercontent.com/4030477/156444158-9c009251-b62d-43d5-a257-a8e3419ccf18.jpg)
![Screen_splash](https://user-images.githubusercontent.com/4030477/156444205-fedfafb4-75b7-4bcb-82a4-21cc0d08d12a.png)

### Checklist

- [ ] Make background change ´#9DBDFD´ .
- [ ] Make icon change, center it with respect to the page.

### References
(https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=803%3A839)

**Comment by Eghinner** [comment]
Can I take it?

**Comment by heliomar-pena** [comment]
Of course! @Eghinner

**Comment by Eghinner** [comment]
@Katsu08, I have a question. It is something like [This](https://nguyenbathanh.github.io/)

**Comment by heliomar-pena** [comment]
@Eghinner Yes! I think it's called "Splashscreen"
