### ISSUE TITLE
Change Ticket View Button Size

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#83]
### Explanation:

Leave the button the size of the text field, check in which other views the component is used. In the other view you see two buttons and in this one only one and check that it looks good on the different mobile and desktop screens, link attached to Figma for the design guide.

### Screenshots
![view_start](https://user-images.githubusercontent.com/4030477/156786477-34651ba7-7d6f-4ebe-8c1b-755488256cab.jpg)

### Checklist

- [ ] Check Used Button Component
- [ ] Review the different resolutions that look good.

### References
(https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46)

**Comment by arodriguezl9302** [comment]
I would like to do this task

**Comment by mdrianislam0or1** [comment]
Hello.. I want to do this task.
