### ISSUE TITLE
   Fix Image Position "Confirm" View.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/maps-project#88]
### Explanation:

I have seen that at  "confirm" view the image is poorly positioned in some screen sizes, this topic is to improve this:

### Screenshots

case 1: Desktop > 1326px. The image is hiding in the bottom of the page
![imagen](https://user-images.githubusercontent.com/66505715/157508137-b6a36784-70ad-4113-aa8d-7e042e414a63.png)

case 2: Tablet  > 600px AND < 946px. The image is overflow the container
![imagen](https://user-images.githubusercontent.com/66505715/157508491-9a948a2d-dc44-4eb6-9776-b2e680039c5a.png)

case 3: Tablet > 972px AND < 1024px The image is so big, please check how to fix it.
![imagen](https://user-images.githubusercontent.com/66505715/157508582-8924d37f-ca4b-4cae-ba24-6404a36c57e6.png)

### Checklist

This issue can be closed when the following tasks are completed:

- [ ] Please, fix all cases that I've left in the screenshots.

**Comment by mdibuhossain** [comment]
I want to be assigned
