### ISSUE TITLE
Check Why EsLint Is Not Working At The Project.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/maps-project#92]
**Describe the bug**
I have noticed that when I run `npm run eslint` always say "0 Error, 0 Warnings", until when exists errors and warnings to fix.

**To Reproduce**
1. Open the project.
2. Create an error of indentation, miss a `;`, etc...
3. Run `npm run eslint`

**Expected behavior**
Running Eslint we're get the actual eslint errors.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/66505715/157752301-eb138c71-957b-461e-8055-fea6a3883d11.png)

You may need to install EsLint or configure it.

**Comment by mdrianislam0or1** [comment]
I want to be assigned to this task.

**Comment by heliomar-pena** [comment]
Great! You're now assigned to this task
