### ISSUE TITLE
Change View Ticket Styles, Report and Home

### ISSUE THREAD

**Issue by angelik0828** [Azordev/maps-project#95]
### Explanation:
In the entry view of the ticket number and in the report view where there are three text fields and one respectively, these texts must be centered, they give the appearance of being misaligned, the dasher logo appears on the home page, it must be put off .

### Screenshots

![image](https://user-images.githubusercontent.com/4030477/158417550-11999817-7d7f-4771-9799-df896f718a7d.png)

### Checklist

- [ ] Align texts in ticket view.
- [ ]  Align texts in report view.

### References

(https://www.figma.com/file/tbhMgDT10bbVjB9GazF97y/Dasher?node-id=407%3A46)

**Comment by heliomar-pena** [comment]
Humm the Dasher logo task can be handle in #54 . And this issue can be just about center confirm input placeholder text

**Comment by heliomar-pena** [comment]
I was made the change in the issue
